export const JPTEN_CLICK = 'JPTEN_CLICK';
export const JPTEN_VALIDTIME_CHANGE = 'JPTEN_VALIDTIME_CHANGE';
export const JPTEN_TYPE_CHECK = 'JPTEN_TYPE_CHECK';
export const JPTEN_PAST_CHANGE = 'JPTEN_PAST_CHANGE';
export const JPTEN_TIMELIST = 'JPTEN_TIMELIST';
