export const HILOFRONT_SHOW_CLICK = 'HILOFRONT_SHOW_CLICK';

export const HILOFRONT_BASETIME_CHANGE = 'HILOFRONT_BASETIME_CHANGE';
export const HILOFRONT_VALIDTIME_CHANGE = 'HILOFRONT_VALIDTIME_CHANGE';

export const HILOFRONT_CONTOUR_CLICK = 'HILOFRONT_CONTOUR_CLICK';
export const HILOFRONT_HILO_CLICK = 'HILOFRONT_HILO_CLICK';
export const HILOFRONT_FRONT_CLICK = 'HILOFRONT_FRONT_CLICK';

export const HILOFRONT_TIMELIST = 'HILOFRONT_TIMELIST';
export const HILOFRONT_INITIALIZE = 'HILOFRONT_INITIALIZE';

export const HILOFRONT_WRAP_DISPATCH_ACTION = 'HILOFRONT_WRAP_DISPATCH_ACTION';
