export const RADAR_CLICK = 'RADAR_CLICK';
export const RADAR_COVERAGE_CLICK = 'RADAR_COVERAGE_CLICK';
export const JP_RADAR_CLICK = 'JP_RADAR_CLICK';
export const JP_RADAR_VALIDTIME_CHANGE = 'JP_RADAR_VALIDTIME_CHANGE';

export const US_AK_RADAR_CLICK = 'US_AK_RADAR_CLICK';
export const US_AK_RADAR_VALIDTIME_CHANGE = 'US_AK_RADAR_VALIDTIME_CHANGE';
export const US_GU_RADAR_CLICK = 'US_GU_RADAR_CLICK';
export const US_GU_RADAR_VALIDTIME_CHANGE = 'US_GU_RADAR_VALIDTIME_CHANGE';
export const US_HI_RADAR_CLICK = 'US_HI_RADAR_CLICK';
export const US_HI_RADAR_VALIDTIME_CHANGE = 'US_HI_RADAR_VALIDTIME_CHANGE';
export const US_NA_RADAR_CLICK = 'US_NA_RADAR_CLICK';
export const US_NA_RADAR_VALIDTIME_CHANGE = 'US_NA_RADAR_VALIDTIME_CHANGE';
export const US_PR_RADAR_CLICK = 'US_PR_RADAR_CLICK';
export const US_PR_RADAR_VALIDTIME_CHANGE = 'US_PR_RADAR_VALIDTIME_CHANGE';

export const EU_RADAR_CLICK = 'EU_RADAR_CLICK';
export const EU_RADAR_VALIDTIME_CHANGE = 'EU_RADAR_VALIDTIME_CHANGE';
export const AU_RADAR_CLICK = 'AU_RADAR_CLICK';
export const AU_RADAR_VALIDTIME_CHANGE = 'AU_RADAR_VALIDTIME_CHANGE';
export const KR_RADAR_CLICK = 'KR_RADAR_CLICK';
export const KR_RADAR_VALIDTIME_CHANGE = 'KR_RADAR_VALIDTIME_CHANGE';
export const TW_RADAR_CLICK = 'TW_RADAR_CLICK';
export const TW_RADAR_VALIDTIME_CHANGE = 'TW_RADAR_VALIDTIME_CHANGE';
export const JP_ICDB_RADAR_CLICK = 'JP_ICDB_RADAR_CLICK';
export const JP_ICDB_RADAR_VALIDTIME_CHANGE = 'JP_ICDB_RADAR_VALIDTIME_CHANGE';
export const JP_ECHOTOP_CLICK = 'JP_ECHOTOP_CLICK';

export const JP_RADAR_ACTIVITY_REQUEST = 'JP_RADAR_ACTIVITY_REQUEST';
export const JP_RADAR_ACTIVITY_SUCCESS = 'JP_RADAR_ACTIVITY_SUCCESS';
export const JP_RADAR_ACTIVITY_FAILURE = 'JP_RADAR_ACTIVITY_FAILURE';
export const JP_RADAR_ACTIVITY_CHANGE = 'JP_RADAR_ACTIVITY_CHANGE';

export const JMA_PRCRIN_CLICK = 'JMA_PRCRIN_CLICK';
export const JMA_PRCRIN_VALIDTIME_CHANGE = 'JMA_PRCRIN_VALIDTIME_CHANGE';

export const JMA_PRCRIN_EXTRA_CLICK = 'JMA_PRCRIN_EXTRA_CLICK';
export const JMA_PRCRIN_EXTRA_VALIDTIME_CHANGE = 'JMA_PRCRIN_EXTRA_VALIDTIME_CHANGE';

export const EC_OBS_RADAR_ECHINT_CA_CLICK = 'EC_OBS_RADAR_ECHINT_CA_CLICK';
export const EC_OBS_RADAR_ECHINT_CA_VALIDTIME_CHANGE = 'EC_OBS_RADAR_ECHINT_CA_VALIDTIME_CHANGE';

export const WX_JP_RADAR_TIMELIST = 'WX_JP_Radar_TIMELIST';
export const WX_US_AK_RADAR_TIMELIST = 'WX_US_AK_Radar_TIMELIST';
export const WX_US_GU_RADAR_TIMELIST = 'WX_US_GU_Radar_TIMELIST';
export const WX_US_HI_RADAR_TIMELIST = 'WX_US_HI_Radar_TIMELIST';
export const WX_US_NA_RADAR_TIMELIST = 'WX_US_NA_Radar_TIMELIST';
export const WX_US_PR_RADAR_TIMELIST = 'WX_US_PR_Radar_TIMELIST';
export const WX_EU_RADAR_TIMELIST = 'WX_EU_Radar_TIMELIST';
export const WX_AU_RADAR_TIMELIST = 'WX_AU_Radar_TIMELIST';
export const WX_KR_RADAR_TIMELIST = 'WX_KR_Radar_TIMELIST';
export const WX_TW_RADAR_TIMELIST = 'WX_TW_Radar_TIMELIST';
export const JMA_OBS_RADAR_ECHINT_JP_TIMELIST = 'JMA_OBS_RADAR_ECHINT_JP_5min_TIMELIST';
export const JMA_NOWCAS_PRCRIN_TIMELIST = 'JMA_NOWCAS_PRCRIN_TIMELIST';
export const JMA_ANLSIS_PRCRIN_TIMELIST = 'JMA_ANLSIS_PRCRIN_TIMELIST';
export const JMA_ANLSIS_PRCRIN_EXTRA_TIMELIST = 'JMA_ANLSIS_PRCRIN_EXTRA_TIMELIST';
export const EC_OBS_RADAR_ECHINT_CA_TIMELIST = 'EC_OBS_RADAR_ECHINT_CA_TIMELIST';
export const JMA_OBS_RADAR_ECHINT_JP_IMELIST = 'JMA_OBS_RADAR_ECHINT_JP_IMELIST';
