export const GPV_MSMGROUND_CLICK = 'GPV_MSMGROUND_CLICK';
export const GPV_MSMGROUND_WIND_CLICK = 'GPV_MSMGROUND_WIND_CLICK';
export const GPV_MSMGROUND_PRECIPITATION_CLICK = 'GPV_MSMGROUND_PRECIPITATION_CLICK';
export const GPV_MSMGROUND_CONTOUR_CLICK = 'GPV_MSMGROUND_CONTOUR_CLICK';

export const GPV_MSMGROUND_BASETIME_CHANGE = 'GPV_MSMGROUND_BASETIME_CHANGE';
export const GPV_MSMGROUND_VALIDTIME_CHANGE = 'GPV_MSMGROUND_VALIDTIME_CHANGE';
export const GPV_MSMGROUND_TIMELIST = 'GPV_MSMGROUND_TIMELIST';
export const GPV_MSMGROUND_INITIALIZE = 'GPV_MSMGROUND_INITIALIZE';
