export const ICE_CONCENTRATION_CLICK = 'ICE_CONCENTRATION_CLICK';
export const ICE_CONCENTRATION_BASETIME_CHANGE = 'ICE_CONCENTRATION_BASETIME_CHANGE';
export const ICE_CONCENTRATION_VALIDTIME_CHANGE = 'ICE_CONCENTRATION_VALIDTIME_CHANGE';
export const ICE_CONCENTRATION_TIMELIST = 'ICE_CONCENTRATION_TIMELIST';
