export const ASC_CLICK = 'ASC_CLICK';
export const ASC_VALIDTIME_CHANGE = 'ASC_VALIDTIME_CHANGE';
export const ASC_LEVEL_START_CHANGE = 'ASC_LEVEL_START_CHANGE';
export const ASC_LEVEL_END_CHANGE = 'ASC_LEVEL_END_CHANGE';
export const ASC_TURBULENCE_CLICK = 'ASC_TURBULENCE_CLICK';
export const ASC_CONVECTION_CLICK = 'ASC_CONVECTION_CLICK';
export const ASC_ICING_CLICK = 'ASC_ICING_CLICK';

export const ASC_TIMELIST = 'ASC_TIMELIST';

export const ASC_INITIALIZE = 'ASC_INITIALIZE';

export const WRAP_DISPATCH_ACTION = 'WRAP_DISPATCH_ACTION';
