export const SEA_VISIBILITY_CLICK = 'SEA_VISIBILITY_CLICK';
export const SEA_VISIBILITY_BASETIME_CHANGE = 'SEA_VISIBILITY_BASETIME_CHANGE';
export const SEA_VISIBILITY_VALIDTIME_CHANGE = 'SEA_VISIBILITY_VALIDTIME_CHANGE';
export const SEA_VISIBILITY_TIMELIST = 'SEA_VISIBILITY_TIMELIST';
