
export const ONLINE = 'ONLINE';
export const OFFLINE = 'OFFLINE';

export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const CHANGE_SHOW_CONTENTS = 'CHANGE_SHOW_CONTENTS';
export const PREPARE = 'PREPARE';

export const MAP_OPT_REQUEST = 'MAP_OPT_REQUEST';
export const MAP_OPT_SUCCESS = 'MAP_OPT_SUCCESS';
export const MAP_OPT_FAILURE = 'MAP_OPT_FAILURE';

export const MAP_SWITCH_GMAP = 'MAP_SWITCH_GMAP';
export const MAP_SWITCH_OLMAP = 'MAP_SWITCH_OLMAP';
export const MAP_SWITCH_OLPOLARMAP = 'MAP_SWITCH_OLPOLARMAP';
export const MAP_SWITCH_WEBGLMAP = 'MAP_SWITCH_WEBGLMAP';
export const MAP_SWITCH_WEBGLPOLARMAP = 'MAP_SWITCH_WEBGLPOLARMAP';
export const MAP_CHANGE_MAP_SOURCE = 'MAP_CHANGE_MAP_SOURCE';

export const LEGEND_SHOW = 'LEGEND_SHOW';
export const LEGEND_ADD = 'LEGEND_ADD';
export const LEGEND_DELETE = 'LEGEND_DELETE';
export const LEGEND_CHANGE_SIZE = 'LEGEND_CHANGE_SIZE';
export const LEGEND_CHANGE_LEFT = 'LEGEND_CHANGE_LEFT';

export const GRAPH_REQUEST = 'GRAPH_REQUEST';
export const GRAPH_SUCCESS = 'GRAPH_SUCCESS';
export const GRAPH_FAILURE = 'GRAPH_FAILURE';

export const WRAP_DISPATCH_ACTION = 'WRAP_DISPATCH_ACTION';

export const ADD_CHECKED_FUNCTION = 'ADD_CHECKED_FUNCTION';
export const REMOVE_FUNCTION_LIST = 'REMOVE_FUNCTION_LIST';

export const LAYER_INITIALIZE = 'LAYER_INITIALIZE';
export const STORE_INITIALIZE = 'STORE_INITIALIZE';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
