export const LIGHTNING_JP_CLICK = 'LIGHTNING_JP_CLICK';
export const LIGHTNING_KMA_CLICK = 'LIGHTNING_KMA_CLICK';
export const LIGHTNING_LIDEN_CLICK = 'LIGHTNING_LIDEN_CLICK';
export const LIGHTNING_SET_BASETIME = 'LIGHTNING_SET_BASETIME';
