export const SATELLITE_CLICK = 'SATELLITE_CLICK';
export const SATELLITE_TOOLTIP_CLICK = 'SATELLITE_TOOLTIP_CLICK';
export const SAT_TYPE_CHANGE = 'SAT_TYPE_CHANGE';
export const SAT_VALIDTIME_CHANGE = 'SAT_VALIDTIME_CHANGE';

export const SATELLITE_INITIALIZE = 'SATELLITE_INITIALIZE';

export const SAT_WORLD_WV_VALIDTIME = 'SAT_WORLD_WV_VALIDTIME';
export const SAT_WORLD_IR_VALIDTIME = 'SAT_WORLD_IR_VALIDTIME';
export const SAT_WORLD_CLDTOP_VALIDTIME = 'SAT_WORLD_CLDTOP_VALIDTIME';
export const HIMA8_JP_WV_VALIDTIME = 'HIMA8_JP_WV_VALIDTIME';
export const HIMA8_JP_VIS_VALIDTIME = 'HIMA8_JP_VIS_VALIDTIME';
export const HIMA8_JP_IR_VALIDTIME = 'HIMA8_JP_IR_VALIDTIME';
export const HIMA8_JP_CLDTOP_VALIDTIME = 'HIMA8_JP_CLDTOP_VALIDTIME';
export const MSG_FD_VIS_VALIDTIME = 'MSG_FD_VIS_VALIDTIME';
export const MSG_FD_IR_VALIDTIME = 'MSG_FD_IR_VALIDTIME';
export const MSG_FD_WV_VALIDTIME = 'MSG_FD_WV_VALIDTIME';
export const MSG_FD_CLDTOP_VALIDTIME = 'MSG_FD_CLDTOP_VALIDTIME';
export const MSG_IODC_FD_VIS_VALIDTIME = 'MSG_IODC_FD_VIS_VALIDTIME';
export const MSG_IODC_FD_IR_VALIDTIME = 'MSG_IODC_FD_IR_VALIDTIME';
export const MSG_IODC_FD_WV_VALIDTIME = 'MSG_IODC_FD_WV_VALIDTIME';
export const MSG_IODC_FD_CLDTOP_VALIDTIME = 'MSG_IODC_FD_CLDTOP_VALIDTIME';

