export const JMASEAWARN_CLICK = 'JMASEAWARN_CLICK';

export const JMASEAWARN_INITIALIZE = 'JMASEAWARN_INITIALIZE';

export const JMASEAWARN_ANNOUNCED_DATE = 'JMASEAWARN_ANNOUNCED_DATE';

export const JMASEAWARNFORECAST_ANNOUNCED_DATE = 'JMASEAWARNFORECAST_ANNOUNCED_DATE';

export const JMASEAWARN_SHOWTYPE_CHANGE = 'JMASEAWARN_SHOWTYPE_CHANGE';
