export const WIND_BARBS_CLICK = 'WIND_BARBS_CLICK';
export const WIND_BARBS_BASETIME_CHANGE = 'WIND_BARBS_BASETIME_CHANGE';
export const WIND_BARBS_VALIDTIME_CHANGE = 'WIND_BARBS_VALIDTIME_CHANGE';
export const WIND_BARBS_THRESHOLD_CHANGE = 'WIND_BARBS_THRESHOLD_CHANGE';
export const WIND_BARBS_TIMELIST = 'WIND_BARBS_TIMELIST';
