import { createActions } from 'redux-actions';
import {
  TROPICALSTORM_CLICK,
  TS_CHANGE,
  TS_HISTORY_CLICK,
  JMA_CLICK,
  WNI_CLICK,
  JTWC_CLICK,
  JMA_CHANGE,
  WNI_CHANGE,
  JTWC_CHANGE,
  JMA_TRACK_CLICK,
  JMA_LOW_CLICK,
  JMA_ESTIMATE_CLICK,
  JMA_F_TRACK_CLICK,
  JMA_F_CIRCLE_CLICK,
  JMA_WIND_CLICK,
  JMA_F_WIND_CLICK,
  WNI_TRACK_CLICK,
  WNI_F_TRACK_CLICK,
  WNI_WIND_CLICK,
  WNI_F_WIND_CLICK,
  JTWC_TRACK_CLICK,
  JTWC_F_TRACK_CLICK,
  JTWC_WIND_CLICK,
  JTWC_F_WIND_CLICK,
  JMA_HIST_CHANGE,
  JMA5_F_TRACK_CLICK,
  JMA5_F_CIRCLE_CLICK,
  TROPICALSTORM_LEGEND_TOGGLE,
  JMA_INFO_CHANGE,
  JMA3_WNI_CLICK,
  JMA3_JTWC_CLICK,
  WNI_RELATION_TYPH_CHANGE,
} from '../constants/tropicalstorm/ActionTypes';
import {
  LEGEND_SHOW,
} from '../constants/ActionTypes';
/* eslint-disable camelcase */
import {
  JMA_Typhoon,
  JMA_Typhoon_5days,
  JTWC_Typhoon,
  WNI_TropicalStorm,
  TS_Relation_WNI,
  TS_Relation_JTWC,
  AnalogousTropicalStorm_0,
  AnalogousTropicalStorm_1,
  AnalogousTropicalStorm_2,
} from '../layers/LayerConfig';

const targetLayer = [
  JMA_Typhoon.layerName,
  JMA_Typhoon_5days.layerName,
  JTWC_Typhoon.layerName,
  WNI_TropicalStorm.layerName,
  TS_Relation_WNI.layerName,
  TS_Relation_JTWC.layerName,
  AnalogousTropicalStorm_0.layerName,
  AnalogousTropicalStorm_1.layerName,
  AnalogousTropicalStorm_2.layerName,
];

const checkAction = checked => ({ checked, targetLayer });
const valueAction = value => ({ value, targetLayer });
const toggleAction = toggled => ({ toggled });

export const {
  tropicalstormClick,
  tsChange,
  tsHistoryClick,
  jmaClick,
  wniClick,
  jtwcClick,
  jmaChange,
  wniChange,
  jtwcChange,
  jmaTrackClick,
  jmaLowClick,
  jmaEstimateClick,
  jmaFTrackClick,
  jmaFCircleClick,
  jmaWindClick,
  jmaFWindClick,
  wniTrackClick,
  wniFTrackClick,
  wniWindClick,
  wniFWindClick,
  jtwcTrackClick,
  jtwcFTrackClick,
  jtwcWindClick,
  jtwcFWindClick,
  jmaHistChange,
  jma5FTrackClick,
  jma5FCircleClick,
  tropicalstormLegendToggle,
  legendShow,
  jmaInfoChange,
  jma3WniClick,
  jma3JtwcClick,
  wniRelationTyphChange,
} = createActions({
  [TROPICALSTORM_CLICK]: checkAction,
  [TS_CHANGE]: valueAction,
  [TS_HISTORY_CLICK]: checkAction,
  [JMA_CLICK]: checkAction,
  [WNI_CLICK]: checkAction,
  [JTWC_CLICK]: checkAction,
  [JMA_CHANGE]: valueAction,
  [WNI_CHANGE]: valueAction,
  [JTWC_CHANGE]: valueAction,
  [JMA_TRACK_CLICK]: checkAction,
  [JMA_LOW_CLICK]: checkAction,
  [JMA_ESTIMATE_CLICK]: checkAction,
  [JMA_F_TRACK_CLICK]: checkAction,
  [JMA_F_CIRCLE_CLICK]: checkAction,
  [JMA_WIND_CLICK]: checkAction,
  [JMA_F_WIND_CLICK]: checkAction,
  [WNI_TRACK_CLICK]: checkAction,
  [WNI_F_TRACK_CLICK]: checkAction,
  [WNI_WIND_CLICK]: checkAction,
  [WNI_F_WIND_CLICK]: checkAction,
  [JTWC_TRACK_CLICK]: checkAction,
  [JTWC_F_TRACK_CLICK]: checkAction,
  [JTWC_WIND_CLICK]: checkAction,
  [JTWC_F_WIND_CLICK]: checkAction,
  [JMA_HIST_CHANGE]: valueAction,
  [JMA5_F_TRACK_CLICK]: checkAction,
  [JMA5_F_CIRCLE_CLICK]: checkAction,
  [TROPICALSTORM_LEGEND_TOGGLE]: toggleAction,
  [LEGEND_SHOW]: checkAction,
  [JMA_INFO_CHANGE]: valueAction,
  [JMA3_WNI_CLICK]: checkAction,
  [JMA3_JTWC_CLICK]: checkAction,
  [WNI_RELATION_TYPH_CHANGE]: valueAction,
});

