export const SURFACE_PRESSURE_CLICK = 'SURFACE_PRESSURE_CLICK';
export const SURFACE_PRESSURE_BASETIME_CHANGE = 'SURFACE_PRESSURE_BASETIME_CHANGE';
export const SURFACE_PRESSURE_VALIDTIME_CHANGE = 'SURFACE_PRESSURE_VALIDTIME_CHANGE';
export const SURFACE_PRESSURE_TIMELIST = 'SURFACE_PRESSURE_TIMELIST';
