export const HOURLYANALYSIS_CLICK = 'HOURLYANALYSIS_CLICK';

export const HOURLYANALYSIS_BASETIME_CHANGE = 'HOURLYANALYSIS_BASETIME_CHANGE';
export const HOURLYANALYSIS_VALIDTIME_CHANGE = 'HOURLYANALYSIS_VALIDTIME_CHANGE';

export const HOURLYANALYSIS_WIND_CLICK = 'HOURLYANALYSIS_WIND_CLICK';
export const HOURLYANALYSIS_TMP_CLICK = 'HOURLYANALYSIS_TMP_CLICK';
export const HOURLYANALYSIS_LEVEL_CHANGE = 'HOURLYANALYSIS_LEVEL_CHANGE';


export const HOURLYANALYSIS_TIMELIST = 'HOURLYANALYSIS_TIMELIST';
