export const CURRENT_CLICK = 'CURRENT_CLICK';
export const CURRENT_BASETIME_CHANGE = 'CURRENT_BASETIME_CHANGE';
export const CURRENT_VALIDTIME_CHANGE = 'CURRENT_VALIDTIME_CHANGE';
export const CURRENT_THRESHOLD_CHANGE = 'CURRENT_THRESHOLD_CHANGE';
export const CURRENT_TIMELIST = 'CURRENT_TIMELIST';
