// General
export const WAVE_BLEND_BASETIME_CHANGE = 'WAVE_BLEND_BASETIME_CHANGE';
export const WAVE_BLEND_VALIDTIME_CHANGE = 'WAVE_BLEND_VALIDTIME_CHANGE';
export const WAVE_BLEND_TIMELIST = 'WAVE_BLEND_TIMELIST';
// MAIN
export const WAVE_BLEND_CLICK = 'WAVE_BLEND_CLICK';
// DISPLAY CONTROL
export const WAVE_BLEND_ARROW_CLICK = 'WAVE_BLEND_ARROW_CLICK';
export const WAVE_BLEND_CONTOUR_CLICK = 'WAVE_BLEND_CONTOUR_CLICK';
export const WAVE_BLEND_FLAT_CLICK = 'WAVE_BLEND_FLAT_CLICK';
// DATA CONTROL
export const WAVE_BLEND_LOWRESO_CLICK = 'WAVE_BLEND_LOWRESO_CLICK';
export const WAVE_BLEND_NPAC_CLICK = 'WAVE_BLEND_NPAC_CLICK';
export const WAVE_BLEND_NATL_CLICK = 'WAVE_BLEND_NATL_CLICK';
export const WAVE_BLEND_SEASIA_CLICK = 'WAVE_BLEND_SEASIA_CLICK';
// THRESHOLD
export const WAVE_BLEND_LOWTHRESHOLD_CHANGE = 'WAVE_BLEND_LOWTHRESHOLD_CHANGE';
export const WAVE_BLEND_HIGHTHRESHOLD_CHANGE = 'WAVE_BLEND_HIGHTHRESHOLD_CHANGE';
