export const DASH_CLICK = 'DASH_CLICK';
export const DANGER_CLICK = 'DANGER_CLICK';
export const SEVERE_CLICK = 'SEVERE_CLICK';
export const HEAVY_CLICK = 'HEAVY_CLICK';
export const DASH_BASETIME_CHANGE = 'DASH_BASETIME_CHANGE';
export const DASH_VALIDTIME_CHANGE = 'DASH_VALIDTIME_CHANGE';
export const DASH_TIMELIST = 'DASH_TIMELIST';
