export const SIGWX_CLICK = 'SIGWX_CLICK';
export const SIGWX_CHANGE = 'SIGWX_CHANGE';

export const SIGWX_INITIALIZE = 'SIGWX_INITIALIZE';
export const SIGWX_WRAP_DISPATCH_ACTION = 'SIGWX_WRAP_DISPATCH_ACTION';

export const UK_HIGH_CLICK = 'UK_HIGH_CLICK';
export const UK_HIGH_BASETIME_CHANGE = 'UK_HIGH_BASETIME_CHANGE';
export const UK_HIGH_VALIDTIME_CHANGE = 'UK_HIGH_VALIDTIME_CHANGE';

export const UK_MIDDLE_CLICK = 'UK_MIDDLE_CLICK';
export const UK_MIDDLE_BASETIME_CHANGE = 'UK_MIDDLE_BASETIME_CHANGE';
export const UK_MIDDLE_VALIDTIME_CHANGE = 'UK_MIDDLE_VALIDTIME_CHANGE';

export const US_HIGH_CLICK = 'US_HIGH_CLICK';
export const US_HIGH_BASETIME_CHANGE = 'US_HIGH_BASETIME_CHANGE';
export const US_HIGH_VALIDTIME_CHANGE = 'US_HIGH_VALIDTIME_CHANGE';

export const US_MIDDLE_CLICK = 'US_MIDDLE_CLICK';
export const US_MIDDLE_BASETIME_CHANGE = 'US_MIDDLE_BASETIME_CHANGE';
export const US_MIDDLE_VALIDTIME_CHANGE = 'US_MIDDLE_VALIDTIME_CHANGE';

export const SIGWX_UK_HIGHT_PAST_TIMELIST = 'SIGWX_UK_High_past_TIMELIST';
export const SIGWX_UK_MIDDLE_PAST_TIMELIST = 'SIGWX_UK_Middle_past_TIMELIST';
export const SIGWX_US_HIGHT_PAST_TIMELIST = 'SIGWX_US_High_past_TIMELIST';
export const SIGWX_US_MIDDLE_PAST_TIMELIST = 'SIGWX_US_Middle_past_TIMELIST';
