export const BASICTEST_CHECK = 'BASICTEST_CHECK';
export const BASICTEST_ELEMENT_CHANGE = 'BASICTEST_ELEMENT_CHANGE';
export const BASICTEST_LON_OFFSET = 'BASICTEST_LON_OFFSET';
export const BASICTEST_LON_NORMALIZE = 'BASICTEST_LON_NORMALIZE';
