export const WRAP_DISPATCH_ACTION = 'WRAP_DISPATCH_ACTION';

/* GSM */
export const GPV_GSM_CLICK = 'GPV_GSM_CLICK';
export const GPV_GSM_WIND_CLICK = 'GPV_GSM_WIND_CLICK';
export const GPV_GSM_ISOTACH_CLICK = 'GPV_GSM_ISOTACH_CLICK';
export const GPV_GSM_VALIDTIME_CHANGE = 'GPV_GSM_VALIDTIME_CHANGE';
export const GPV_GSM_LEVEL_CHANGE = 'GPV_GSM_LEVEL_CHANGE';
export const GPV_GSM_TIMELIST = 'GPV_GSM_TIMELIST';

export const GPV_GSM_TEMP_CLICK = 'GPV_GSM_TEMP_CLICK';
export const GPV_GSM_TMP_CONTOUR_CLICK = 'GPV_GSM_TMP_CONTOUR_CLICK';
export const GPV_GSM_TMP_FLAT_CLICK = 'GPV_GSM_TMP_FLAT_CLICK';
export const GPV_GSM_TMP_GRADATION_CLICK = 'GPV_GSM_TMP_GRADATION_CLICK';
export const GPV_GSM_TMP_GRIDVALUE_CLICK = 'GPV_GSM_TMP_GRIDVALUE_CLICK';

export const GPV_GSM_HGT_CLICK = 'GPV_GSM_HGT_CLICK';
export const GPV_GSM_HGT_CONTOUR_CLICK = 'GPV_GSM_HGT_CONTOUR_CLICK';
export const GPV_GSM_HGT_FLAT_CLICK = 'GPV_GSM_HGT_FLAT_CLICK';
export const GPV_GSM_HGT_GRADATION_CLICK = 'GPV_GSM_HGT_GRADATION_CLICK';
export const GPV_GSM_HGT_GRIDVALUE_CLICK = 'GPV_GSM_HGT_GRIDVALUE_CLICK';

export const GPV_GSM_RH_CLICK = 'GPV_GSM_RH_CLICK';
export const GPV_GSM_RH_CONTOUR_CLICK = 'GPV_GSM_RH_CONTOUR_CLICK';
export const GPV_GSM_RH_FLAT_CLICK = 'GPV_GSM_RH_FLAT_CLICK';
export const GPV_GSM_RH_GRADATION_CLICK = 'GPV_GSM_RH_GRADATION_CLICK';
export const GPV_GSM_RH_GRIDVALUE_CLICK = 'GPV_GSM_RH_GRIDVALUE_CLICK';

export const GPV_GSM_ICING_PROB_CLICK = 'GPV_GSM_ICING_PROB_CLICK';

export const GPV_GSM_PRECIPITATION_CLICK = 'GPV_GSM_PRECIPITATION_CLICK';
export const GPV_GSM_PRECIPITATION_FLAT_CLICK = 'GPV_GSM_PRECIPITATION_FLAT_CLICK';
export const GPV_GSM_PRECIPITATION_GRADATION_CLICK = 'GPV_GSM_PRECIPITATION_GRADATION_CLICK';

/* UKMET */
export const GPV_UKMET_CLICK = 'GPV_UKMET_CLICK';
export const GPV_UKMET_WIND_CLICK = 'GPV_UKMET_WIND_CLICK';
export const GPV_UKMET_ISOTACH_CLICK = 'GPV_UKMET_ISOTACH_CLICK';
export const GPV_UKMET_VALIDTIME_CHANGE = 'GPV_UKMET_VALIDTIME_CHANGE';
export const GPV_UKMET_LEVEL_CHANGE = 'GPV_UKMET_LEVEL_CHANGE';
export const GPV_UKMET_TIMELIST = 'GPV_UKMET_TIMELIST';

export const GPV_UKMET_TEMP_CLICK = 'GPV_UKMET_TEMP_CLICK';
export const GPV_UKMET_TMP_CONTOUR_CLICK = 'GPV_UKMET_TMP_CONTOUR_CLICK';
export const GPV_UKMET_TMP_FLAT_CLICK = 'GPV_UKMET_TMP_FLAT_CLICK';
export const GPV_UKMET_TMP_GRADATION_CLICK = 'GPV_UKMET_TMP_GRADATION_CLICK';
export const GPV_UKMET_TMP_GRIDVALUE_CLICK = 'GPV_UKMET_TMP_GRIDVALUE_CLICK';

export const GPV_UKMET_HGT_CLICK = 'GPV_UKMET_HGT_CLICK';
export const GPV_UKMET_HGT_CONTOUR_CLICK = 'GPV_UKMET_HGT_CONTOUR_CLICK';
export const GPV_UKMET_HGT_FLAT_CLICK = 'GPV_UKMET_HGT_FLAT_CLICK';
export const GPV_UKMET_HGT_GRADATION_CLICK = 'GPV_UKMET_HGT_GRADATION_CLICK';
export const GPV_UKMET_HGT_GRIDVALUE_CLICK = 'GPV_UKMET_HGT_GRIDVALUE_CLICK';

export const GPV_UKMET_RH_CLICK = 'GPV_UKMET_RH_CLICK';
export const GPV_UKMET_RH_CONTOUR_CLICK = 'GPV_UKMET_RH_CONTOUR_CLICK';
export const GPV_UKMET_RH_FLAT_CLICK = 'GPV_UKMET_RH_FLAT_CLICK';
export const GPV_UKMET_RH_GRADATION_CLICK = 'GPV_UKMET_RH_GRADATION_CLICK';
export const GPV_UKMET_RH_GRIDVALUE_CLICK = 'GPV_UKMET_RH_GRIDVALUE_CLICK';

export const GPV_UKMET_ICING_PROB_CLICK = 'GPV_UKMET_ICING_PROB_CLICK';

/* GFS */
export const GPV_GFS_CLICK = 'GPV_GFS_CLICK';
export const GPV_GFS_WIND_CLICK = 'GPV_GFS_WIND_CLICK';
export const GPV_GFS_ISOTACH_CLICK = 'GPV_GFS_ISOTACH_CLICK';
export const GPV_GFS_VALIDTIME_CHANGE = 'GPV_GFS_VALIDTIME_CHANGE';
export const GPV_GFS_LEVEL_CHANGE = 'GPV_GFS_LEVEL_CHANGE';
export const GPV_GFS_TIMELIST = 'GPV_GFS_TIMELIST';

export const GPV_GFS_TEMP_CLICK = 'GPV_GFS_TEMP_CLICK';
export const GPV_GFS_TMP_CONTOUR_CLICK = 'GPV_GFS_TMP_CONTOUR_CLICK';
export const GPV_GFS_TMP_FLAT_CLICK = 'GPV_GFS_TMP_FLAT_CLICK';
export const GPV_GFS_TMP_GRADATION_CLICK = 'GPV_GFS_TMP_GRADATION_CLICK';
export const GPV_GFS_TMP_GRIDVALUE_CLICK = 'GPV_GFS_TMP_GRIDVALUE_CLICK';

export const GPV_GFS_HGT_CLICK = 'GPV_GFS_HGT_CLICK';
export const GPV_GFS_HGT_CONTOUR_CLICK = 'GPV_GFS_HGT_CONTOUR_CLICK';
export const GPV_GFS_HGT_FLAT_CLICK = 'GPV_GFS_HGT_FLAT_CLICK';
export const GPV_GFS_HGT_GRADATION_CLICK = 'GPV_GFS_HGT_GRADATION_CLICK';
export const GPV_GFS_HGT_GRIDVALUE_CLICK = 'GPV_GFS_HGT_GRIDVALUE_CLICK';

export const GPV_GFS_RH_CLICK = 'GPV_GFS_RH_CLICK';
export const GPV_GFS_RH_CONTOUR_CLICK = 'GPV_GFS_RH_CONTOUR_CLICK';
export const GPV_GFS_RH_FLAT_CLICK = 'GPV_GFS_RH_FLAT_CLICK';
export const GPV_GFS_RH_GRADATION_CLICK = 'GPV_GFS_RH_GRADATION_CLICK';
export const GPV_GFS_RH_GRIDVALUE_CLICK = 'GPV_GFS_RH_GRIDVALUE_CLICK';

export const GPV_GFS_ICING_PROB_CLICK = 'GPV_GFS_ICING_PROB_CLICK';

export const GPV_GFS_PRECIPITATION_CLICK = 'GPV_GFS_PRECIPITATION_CLICK';
export const GPV_GFS_PRECIPITATION_FLAT_CLICK = 'GPV_GFS_PRECIPITATION_FLAT_CLICK';
export const GPV_GFS_PRECIPITATION_GRADATION_CLICK = 'GPV_GFS_PRECIPITATION_GRADATION_CLICK';

export const GPV_GFS_SNOW_DEPTH_CLICK = 'GPV_GFS_SNOW_DEPTH_CLICK';

export const GPV_GFS_PRESSURE_MSL_CLICK = 'GPV_GFS_PRESSURE_MSL_CLICK';

/* MSM */
export const GPV_MSM_CLICK = 'GPV_MSM_CLICK';
export const GPV_MSM_WIND_CLICK = 'GPV_MSM_WIND_CLICK';
export const GPV_MSM_ISOTACH_CLICK = 'GPV_MSM_ISOTACH_CLICK';
export const GPV_MSM_VALIDTIME_CHANGE = 'GPV_MSM_VALIDTIME_CHANGE';
export const GPV_MSM_LEVEL_CHANGE = 'GPV_MSM_LEVEL_CHANGE';
export const GPV_MSM_TIMELIST = 'GPV_MSM_TIMELIST';

export const GPV_MSM_TEMP_CLICK = 'GPV_MSM_TEMP_CLICK';
export const GPV_MSM_TMP_CONTOUR_CLICK = 'GPV_MSM_TMP_CONTOUR_CLICK';
export const GPV_MSM_TMP_FLAT_CLICK = 'GPV_MSM_TMP_FLAT_CLICK';
export const GPV_MSM_TMP_GRADATION_CLICK = 'GPV_MSM_TMP_GRADATION_CLICK';
export const GPV_MSM_TMP_GRIDVALUE_CLICK = 'GPV_MSM_TMP_GRIDVALUE_CLICK';

export const GPV_MSM_HGT_CLICK = 'GPV_MSM_HGT_CLICK';
export const GPV_MSM_HGT_CONTOUR_CLICK = 'GPV_MSM_HGT_CONTOUR_CLICK';
export const GPV_MSM_HGT_FLAT_CLICK = 'GPV_MSM_HGT_FLAT_CLICK';
export const GPV_MSM_HGT_GRADATION_CLICK = 'GPV_MSM_HGT_GRADATION_CLICK';
export const GPV_MSM_HGT_GRIDVALUE_CLICK = 'GPV_MSM_HGT_GRIDVALUE_CLICK';

export const GPV_MSM_RH_CLICK = 'GPV_MSM_RH_CLICK';
export const GPV_MSM_RH_CONTOUR_CLICK = 'GPV_MSM_RH_CONTOUR_CLICK';
export const GPV_MSM_RH_FLAT_CLICK = 'GPV_MSM_RH_FLAT_CLICK';
export const GPV_MSM_RH_GRADATION_CLICK = 'GPV_MSM_RH_GRADATION_CLICK';
export const GPV_MSM_RH_GRIDVALUE_CLICK = 'GPV_MSM_RH_GRIDVALUE_CLICK';

export const GPV_MSM_ICING_PROB_CLICK = 'GPV_MSM_ICING_PROB_CLICK';
