export const AMEDAS_CLICK = 'AMEDAS_CLICK';

export const AMEDAS_VALIDTIME_CHANGE = 'AMEDAS_VALIDTIME_CHANGE';
export const AMEDAS_WIND_CLICK = 'AMEDAS_WIND_CLICK';
export const AMEDAS_CONTENT_CHANGE = 'AMEDAS_CONTENT_CHANGE';
export const AMEDAS_TIMELIST = 'AMEDAS_TIMELIST';

