// General
export const COMPASS_HOUR_BASETIME_CHANGE = 'COMPASS_HOUR_BASETIME_CHANGE';
export const COMPASS_HOUR_VALIDTIME_CHANGE = 'COMPASS_HOUR_VALIDTIME_CHANGE';
export const COMPASS_HOUR_TIMELIST = 'COMPASS_HOUR_TIMELIST';
// MAIN
export const COMPASS_HOUR_CLICK = 'COMPASS_HOUR_CLICK';
// ELEMENT CONTROL
// TMP
export const COMPASS_HOUR_TMP_CLICK = 'COMPASS_HOUR_TMP_CLICK';
export const COMPASS_HOUR_TMP_CONTOUR_CLICK = 'COMPASS_HOUR_TMPCONTOUR_CLICK';
export const COMPASS_HOUR_TMP_CONTOUR_UNIT = 'COMPASS_HOUR_TMPCONTOUR_UNIT';
export const COMPASS_HOUR_TMP_GRIDVALUE_CLICK = 'COMPASS_HOUR_TMPGRIDVALUE_CLICK';
export const COMPASS_HOUR_TMP_GRIDVALUE_UNIT = 'COMPASS_HOUR_TMPGRIDVALUE_UNIT';
export const COMPASS_HOUR_TMP_FILL_CHANGE = 'COMPASS_HOUR_TMPFILL_CHANGE';
// PRES
export const COMPASS_HOUR_PRES_CLICK = 'COMPASS_HOUR_PRES_CLICK';
export const COMPASS_HOUR_PRES_CONTOUR_CLICK = 'COMPASS_HOUR_PRESCONTOUR_CLICK';
export const COMPASS_HOUR_PRES_GRIDVALUE_CLICK = 'COMPASS_HOUR_PRESGRIDVALUE_CLICK';
export const COMPASS_HOUR_PRES_FILL_CHANGE = 'COMPASS_HOUR_PRESFILL_CHANGE';
// RH
export const COMPASS_HOUR_RH_CLICK = 'COMPASS_HOUR_RH_CLICK';
export const COMPASS_HOUR_RH_CONTOUR_CLICK = 'COMPASS_HOUR_RHCONTOUR_CLICK';
export const COMPASS_HOUR_RH_GRIDVALUE_CLICK = 'COMPASS_HOUR_RHGRIDVALUE_CLICK';
export const COMPASS_HOUR_RH_FILL_CHANGE = 'COMPASS_HOUR_RHFILL_CHANGE';
// ASNOW
export const COMPASS_HOUR_ASNOW_CLICK = 'COMPASS_HOUR_ASNOW_CLICK';
export const COMPASS_HOUR_ASNOW_CONTOUR_CLICK = 'COMPASS_HOUR_ASNOWCONTOUR_CLICK';
export const COMPASS_HOUR_ASNOW_GRIDVALUE_CLICK = 'COMPASS_HOUR_ASNOWGRIDVALUE_CLICK';
export const COMPASS_HOUR_ASNOW_FILL_CHANGE = 'COMPASS_HOUR_ASNOWFILL_CHANGE';
// APCP
export const COMPASS_HOUR_APCP_CLICK = 'COMPASS_HOUR_APCP_CLICK';
export const COMPASS_HOUR_APCP_CONTOUR_CLICK = 'COMPASS_HOUR_APCPCONTOUR_CLICK';
export const COMPASS_HOUR_APCP_GRIDVALUE_CLICK = 'COMPASS_HOUR_APCPGRIDVALUE_CLICK';
export const COMPASS_HOUR_APCP_FILL_CHANGE = 'COMPASS_HOUR_APCPFILL_CHANGE';
// POP
export const COMPASS_HOUR_POP_CLICK = 'COMPASS_HOUR_POP_CLICK';
export const COMPASS_HOUR_POP_CONTOUR_CLICK = 'COMPASS_HOUR_POPCONTOUR_CLICK';
export const COMPASS_HOUR_POP_GRIDVALUE_CLICK = 'COMPASS_HOUR_POPGRIDVALUE_CLICK';
export const COMPASS_HOUR_POP_FILL_CHANGE = 'COMPASS_HOUR_POPFILL_CHANGE';
// UGRD, VGRD
export const COMPASS_HOUR_UGRDVGRD_CLICK = 'COMPASS_HOUR_UGRDVGRD_CLICK';
export const COMPASS_HOUR_UGRDVGRD_BARBS_CLICK = 'COMPASS_HOUR_UGRDVGRDBARBS_CLICK';
export const COMPASS_HOUR_WIND_FLOW_CLICK = 'COMPASS_HOUR_WIND_FLOW_CLICK';
export const COMPASS_HOUR_WIND_LINES_CHANGE = 'COMPASS_HOUR_WIND_LINES_CHANGE';
// VIS
export const COMPASS_HOUR_VIS_CLICK = 'COMPASS_HOUR_VIS_CLICK';
export const COMPASS_HOUR_VIS_CONTOUR_CLICK = 'COMPASS_HOUR_VISCONTOUR_CLICK';
export const COMPASS_HOUR_VIS_GRIDVALUE_CLICK = 'COMPASS_HOUR_VISGRIDVALUE_CLICK';
export const COMPASS_HOUR_VIS_FILL_CHANGE = 'COMPASS_HOUR_VISFILL_CHANGE';
// WIWW
export const COMPASS_HOUR_WIWW_CLICK = 'COMPASS_HOUR_WIWW_CLICK';
export const COMPASS_HOUR_WIWW_CONTOUR_CLICK = 'COMPASS_HOUR_WIWWCONTOUR_CLICK';
export const COMPASS_HOUR_WIWW_GRIDVALUE_CLICK = 'COMPASS_HOUR_WIWWGRIDVALUE_CLICK';
export const COMPASS_HOUR_WIWW_FILL_CHANGE = 'COMPASS_HOUR_WIWWFILL_CHANGE';
