import { createAction, createActions } from 'redux-actions';
import { WRAP_API } from '../middleware/api/wrap';
import {
  RADAR_CLICK,
  RADAR_COVERAGE_CLICK,
  JP_RADAR_CLICK,
  JP_RADAR_VALIDTIME_CHANGE,
  US_AK_RADAR_CLICK,
  US_AK_RADAR_VALIDTIME_CHANGE,
  US_GU_RADAR_CLICK,
  US_GU_RADAR_VALIDTIME_CHANGE,
  US_HI_RADAR_CLICK,
  US_HI_RADAR_VALIDTIME_CHANGE,
  US_NA_RADAR_CLICK,
  US_NA_RADAR_VALIDTIME_CHANGE,
  US_PR_RADAR_CLICK,
  US_PR_RADAR_VALIDTIME_CHANGE,
  EU_RADAR_CLICK,
  EU_RADAR_VALIDTIME_CHANGE,
  AU_RADAR_CLICK,
  AU_RADAR_VALIDTIME_CHANGE,
  KR_RADAR_CLICK,
  KR_RADAR_VALIDTIME_CHANGE,
  TW_RADAR_CLICK,
  TW_RADAR_VALIDTIME_CHANGE,
  JP_ICDB_RADAR_CLICK,
  JP_ICDB_RADAR_VALIDTIME_CHANGE,
  JP_ECHOTOP_CLICK,
  JP_RADAR_ACTIVITY_REQUEST,
  JP_RADAR_ACTIVITY_SUCCESS,
  JP_RADAR_ACTIVITY_FAILURE,
  JP_RADAR_ACTIVITY_CHANGE,
  JMA_PRCRIN_CLICK,
  JMA_PRCRIN_VALIDTIME_CHANGE,
  JMA_PRCRIN_EXTRA_CLICK,
  JMA_PRCRIN_EXTRA_VALIDTIME_CHANGE,
  EC_OBS_RADAR_ECHINT_CA_CLICK,
  EC_OBS_RADAR_ECHINT_CA_VALIDTIME_CHANGE,
} from '../constants/radar/ActionTypes';
import {
  LEGEND_SHOW,
} from '../constants/ActionTypes';
/* eslint-disable camelcase */
import {
  WX_JP_Radar,
  WX_US_AK_Radar,
  WX_US_GU_Radar,
  WX_US_HI_Radar,
  WX_US_NA_Radar,
  WX_US_PR_Radar,
  WX_EU_Radar,
  WX_AU_Radar,
  WX_KR_Radar,
  WX_TW_Radar,
  JMA_OBS_RADAR_ECHINT_JP_5min,
  JMA_OBS_RADAR_ECHTOP_JP,
  JMA_NOWCAS_PRCRIN,
  JMA_ANLSIS_PRCRIN_EXTRA,
  EC_OBS_RADAR_ECHINT_CA,
} from '../layers/LayerConfig';

const targetLayer = [
  WX_JP_Radar.layerName,
  WX_US_AK_Radar.layerName,
  WX_US_GU_Radar.layerName,
  WX_US_HI_Radar.layerName,
  WX_US_NA_Radar.layerName,
  WX_US_PR_Radar.layerName,
  WX_EU_Radar.layerName,
  WX_AU_Radar.layerName,
  WX_KR_Radar.layerName,
  WX_TW_Radar.layerName,
  JMA_OBS_RADAR_ECHINT_JP_5min.layerName,
  JMA_OBS_RADAR_ECHTOP_JP.layerName,
  JMA_NOWCAS_PRCRIN.layerName,
  JMA_ANLSIS_PRCRIN_EXTRA.layerName,
  EC_OBS_RADAR_ECHINT_CA.layerName,
];

const checkAction = checked => ({
  checked,
  targetLayer,
});
const valueAction = value => ({
  value: parseInt(value, 10),
  targetLayer,
});

export const {
  radarClick,
  radarCoverageClick,
  jpRadarClick,
  jpRadarValidtimeChange,
  usAkRadarClick,
  usAkRadarValidtimeChange,
  usGuRadarClick,
  usGuRadarValidtimeChange,
  usHiRadarClick,
  usHiRadarValidtimeChange,
  usNaRadarClick,
  usNaRadarValidtimeChange,
  usPrRadarClick,
  usPrRadarValidtimeChange,
  euRadarClick,
  euRadarValidtimeChange,
  auRadarClick,
  auRadarValidtimeChange,
  krRadarClick,
  krRadarValidtimeChange,
  twRadarClick,
  twRadarValidtimeChange,
  jpRadarActivityChange,
  jmaPrcrinClick,
  jmaPrcrinValidtimeChange,
  jmaPrcrinExtraClick,
  jmaPrcrinExtraValidtimeChange,
  ecObsRadarEchintCaClick,
  ecObsRadarEchintCaValidtimeChange,
  legendShow,
} = createActions({
  [RADAR_CLICK]: checkAction,
  [RADAR_COVERAGE_CLICK]: checkAction,
  [JP_RADAR_CLICK]: checkAction,
  [JP_RADAR_VALIDTIME_CHANGE]: valueAction,
  [US_AK_RADAR_CLICK]: checkAction,
  [US_AK_RADAR_VALIDTIME_CHANGE]: valueAction,
  [US_GU_RADAR_CLICK]: checkAction,
  [US_GU_RADAR_VALIDTIME_CHANGE]: valueAction,
  [US_HI_RADAR_CLICK]: checkAction,
  [US_HI_RADAR_VALIDTIME_CHANGE]: valueAction,
  [US_NA_RADAR_CLICK]: checkAction,
  [US_NA_RADAR_VALIDTIME_CHANGE]: valueAction,
  [US_PR_RADAR_CLICK]: checkAction,
  [US_PR_RADAR_VALIDTIME_CHANGE]: valueAction,
  [EU_RADAR_CLICK]: checkAction,
  [EU_RADAR_VALIDTIME_CHANGE]: valueAction,
  [AU_RADAR_CLICK]: checkAction,
  [AU_RADAR_VALIDTIME_CHANGE]: valueAction,
  [KR_RADAR_CLICK]: checkAction,
  [KR_RADAR_VALIDTIME_CHANGE]: valueAction,
  [TW_RADAR_CLICK]: checkAction,
  [TW_RADAR_VALIDTIME_CHANGE]: valueAction,
  [JP_RADAR_ACTIVITY_CHANGE]: valueAction,
  [JMA_PRCRIN_CLICK]: checkAction,
  [JMA_PRCRIN_VALIDTIME_CHANGE]: valueAction,
  [JMA_PRCRIN_EXTRA_CLICK]: checkAction,
  [JMA_PRCRIN_EXTRA_VALIDTIME_CHANGE]: valueAction,
  [EC_OBS_RADAR_ECHINT_CA_CLICK]: checkAction,
  [EC_OBS_RADAR_ECHINT_CA_VALIDTIME_CHANGE]: valueAction,
  [LEGEND_SHOW]: checkAction,
});

export const jpICDBRadarClick = createAction(JP_ICDB_RADAR_CLICK, checkAction);
export const jpICDBRadarValidtimeChange = createAction(JP_ICDB_RADAR_VALIDTIME_CHANGE, valueAction);
export const jpEchoTopClick = createAction(JP_ECHOTOP_CLICK, checkAction);

// const dataPath = 'https://pt-wrap01.wni.co.jp/WRAP/wrap-pri/data/WX_JP_Radar/';

export const loadJPRadarActivity = createAction(
  WRAP_API,
  (baseurl, code) => ({
    types: [JP_RADAR_ACTIVITY_REQUEST, JP_RADAR_ACTIVITY_SUCCESS, JP_RADAR_ACTIVITY_FAILURE],
    endpoint: `${baseurl}/WRAP/wrap-pri/data/WX_JP_Radar/${code}/activity.json?t=${new Date().getTime()}`,
  }),
);
