export const GASS_CLICK = 'GASS_CLICK';
export const GASS_BASETIME_CHANGE = 'GASS_BASETIME_CHANGE';
export const GASS_VALIDTIME_CHANGE = 'GASS_VALIDTIME_CHANGE';
export const GASS_TIMELIST = 'GASS_TIMELIST';
