export const WORLD_BORDER_CLICK = 'WORLD_BORDER_CLICK';
export const WORLD_COASTLINE_CLICK = 'WORLD_COASTLINE_CLICK';
export const JAPAN_BORDER_CLICK = 'JAPAN_BORDER_CLICK';
export const BLUE_MARBLE_CLICK = 'BLUE_MARBLE_CLICK';

export const TILEDMAP_INITIALIZE = 'TILEDMAP_INITIALIZE';
