export const ICE_BERG_CLICK = 'ICE_BERG_CLICK';
export const ICE_BERG_BASETIME_CHANGE = 'ICE_BERG_BASETIME_CHANGE';
export const ICE_BERG_VALIDTIME_CHANGE = 'ICE_BERG_VALIDTIME_CHANGE';
export const ICE_BERG_THRESHOLD_CHANGE = 'ICE_BERG_THRESHOLD_CHANGE';
export const ICE_BERG_TIMELIST = 'ICE_BERG_TIMELIST';
