export const SEA_SPRAY_ICING_CLICK = 'SEA_SPRAY_ICING_CLICK';
export const SEA_SPRAY_ICING_FLAT_CLICK = 'SEA_SPRAY_ICING_FLAT_CLICK';
export const SEA_SPRAY_ICING_CONTOUR_CLICK = 'SEA_SPRAY_ICING_CONTOUR_CLICK';
export const SEA_SPRAY_ICING_BASETIME_CHANGE = 'SEA_SPRAY_ICING_BASETIME_CHANGE';
export const SEA_SPRAY_ICING_VALIDTIME_CHANGE = 'SEA_SPRAY_ICING_VALIDTIME_CHANGE';
export const SEA_SPRAY_ICING_TIMELIST = 'SEA_SPRAY_ICING_TIMELIST';
