export const AIRPORT_CLICK = 'AIRPORT_CLICK';
export const AIRPORT_ALL_CLICK = 'AIRPORT_ALL_CLICK';
export const AIRPORT_CUM_CLICK = 'AIRPORT_CUM_CLICK';

export const AIRPORT_INITIALIZE = 'AIRPORT_INITIALIZE';
